# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./cmd/tinyclaw

builds:
  - id: tinyclaw
    env:
      - CGO_ENABLED=0
    tags:
      - stdjson
    ldflags:
      - -s -w
      - -X github.com/tinyland-inc/tinyclaw/cmd/tinyclaw/internal.version={{ .Version }}
      - -X github.com/tinyland-inc/tinyclaw/cmd/tinyclaw/internal.gitCommit={{ .ShortCommit }}
      - -X github.com/tinyland-inc/tinyclaw/cmd/tinyclaw/internal.buildTime={{ .Date }}
      - -X github.com/tinyland-inc/tinyclaw/cmd/tinyclaw/internal.goVersion={{ .Env.GOVERSION }}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - riscv64
      - loong64
      - arm
    main: ./cmd/tinyclaw
    ignore:
      - goos: windows
        goarch: arm

dockers_v2:
  - id: tinyclaw
    dockerfile: Dockerfile.goreleaser
    ids:
      - tinyclaw
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/tinyclaw"
      - "docker.io/{{ .Env.DOCKERHUB_IMAGE_NAME }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/riscv64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: tinyclaw
    package_name: tinyclaw
    file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    vendor: tinyclaw
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/tinyclaw
    maintainer: tinyclaw contributors
    description: tinyclaw - a tool for managing and running tasks
    license: MIT
    formats:
      - rpm
      - deb
    bindir: /usr/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# upx:
#    - enabled: true
#      compress: best
#      lzma: true

brews:
  - ids: [tinyclaw]
    repository:
      owner: tinyland-inc
      name: homebrew-tinyclaw
    commit_author:
      name: goreleaser
      email: goreleaser@tinyland.dev
    homepage: https://github.com/tinyland-inc/tinyclaw
    description: "Ultra-lightweight personal AI agent"
    license: MIT
    install: |
      bin.install "tinyclaw"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
